# -*- coding: utf-8 -*-
"""task-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19TM2YR2dCh76onDFyZycEuhIBzq4MO1Y

# TASK 2: Image to Pencil Sketch with Python

Firstly import you opencv module which is cv2
"""

import cv2

"""Next we have to import our image to work on it"""

img = cv2.imread("E:\\Internships\\Data_Science_Intern(LetsGrowMore)\\task-2\\data\\POPPYBELLA_19.jpg")

"""Now we will display our image in array form"""

img

"""Next we will check the shape of our image"""

img.shape

"""In the next step we will display our image

waits for user to press any key 

this is necessary to avoid Python kernel form crashing
"""

cv2.imshow('image',img)
cv2.waitKey(0)

"""Now we will convert our original image to grayscale image and will display the same"""

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow("Image_gray", gray_img)
cv2.waitKey(0)

"""Next we will **invert** our image of grayscale and display it"""

invert_img = 255 - gray_img

cv2.imshow("Inverted Image", invert_img)
cv2.waitKey(0)

"""Next we will blur that inverted image by using gaussian blur function in cv2 module"""

blurred = cv2.GaussianBlur(invert_img, (21, 21), 0)

"""Now in the final step we will again invert our blurred image, and then we will get our pencil sketch of that image"""

invert_blur = 255 - blurred
final_sketch = cv2.divide(gray_img, invert_blur, scale=256.0)

cv2.imshow("Final Pencil Sketch", final_sketch)
cv2.waitKey(0)

